### ISSUE TITLE
[note-to-self] Add E2E tests with Cypress

### ISSUE THREAD

**Issue by benji011** [benji011/portfolio.benjaminlo.io#12]
TODO: Add E2E test with Cypress later.

**Comment by benji011** [comment]
Cypress has now been installed from https://github.com/benji011/portfolio.benjaminlo.io/pull/49
To add the tests, you can refer to the examples in `cypress/integration/`. A good one to start is `/cypress/integration/1-getting-started/todo.spec.js`

Now, adding tests is relatively simple but the examples can be removed after at least 1 good E2E test has been added

**Comment by TheLaw1337** [comment]
Can I take this?

**Comment by TheLaw1337** [comment]
@benji011 done #51
