### ISSUE TITLE
Improve performance - refactor overlay SVG

### ISSUE THREAD

**Issue by benji011** [benji011/portfolio.benjaminlo.io#13]
## What
The white part of this image is an example of these overlay SVG files.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/6195689/95932308-7de9d080-0e06-11eb-8dee-951503abef12.png">

This image changes from light to dark, depending on the theme selected (inverted from dark to light and vice versa)

Code for this is written here
https://github.com/benji011/portfolio.benjaminlo.io/blob/e7c31be7c17ee3694a16894a7db809ff5c08b9a5/src/components/landing/Intro/index.jsx#L10-L20

## Why
I think this could be done better, e.g. keeping just 1 SVG file and update the fill colour instead. It's not an urgent issue but i'm curious if this improves performance.

**Comment by martink-rsa** [comment]
Hi @benji011 

I'd like to handle this please.

**Comment by benji011** [comment]
Thanks @martink-rsa !
All yours

**Comment by martink-rsa** [comment]
@benji011 I'm struggling to find an elegant solution while the SVG is used as the `background-image` property. 

1. The SVG being encoded once imported;
2. Not being able to use a CSS variable.

The easiest would probably be to have the background as an image in absolute position beneath the container. It can then be used as a component which we can pass a prop. 

I have however found a way to get it to work with it being a background-image using base64 encoding. The steps are:

1. Create a function that returns a string of the SVG, passing in a parameter of `fill`. This function also returns a base64 encoded string
2. Run this function and concatenate the required SVG image keywords (`data:image/svg+xml;base64,`)
3. Use this string as the background image string.

![image](https://user-images.githubusercontent.com/52622303/97540021-ac050e00-19cb-11eb-9d07-62e366b9498a.png)

```js
const getIllustration = (fill) =>
  btoa(`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 837.3 703.7">
  <defs>
    <style>
      .a{fill:${fill}}
    </style>
  </defs>
  <path d="M0 0s147.8 100.8 67.5 300.3S620 377.5 620 377.5l-24.2 180.4 40.6 131.5 201-62.8V0z" class="a"/>
  <path d="M439.4 310.9c-45.1-1.6-88-16.1-129-32s-81.5-33.6-125.5-42c-28.3-5.4-60.7-6.2-83.4 9-22 14.6-29 39.7-32.9 63.1-2.8 17.6-4.5 36.1 3.3 52.6 5.5 11.4 15.2 21 21.9 32 23.3 38 6.8 85-18.5 122.2-11.8 17.5-25.5 34.1-34.7 52.7s-13.3 39.8-5.3 58.8C43.2 646 62 660.2 82.5 670c41.6 20.1 90.5 26 138.3 29.2 105.7 7.2 212 4 318 1a934 934 0 0 0 117.1-8.4c21.4-3.4 43.5-8.8 59.1-21.6a49.5 49.5 0 0 0 11.4-64.7c-22.2-34.4-83.5-43-99-80-8.6-20.3.2-43 12.6-61.9 26.6-40.5 71.2-76 73.6-122.3 1.6-31.8-19.9-63.6-53-78.6C625.8 247 577.6 249 552 275c-26.5 26.8-72.9 37.2-112.6 35.8z" class="a"/>
</svg>`);

const overlayIllustrationLight = `data:image/svg+xml;base64,${getIllustration('#272c3e')}`;
const overlayIllustrationDark = `data:image/svg+xml;base64,${getIllustration('#fff')}`;

export const Intro = () => {
  const { theme } = useContext(ThemeContext);
  const overlay =
    theme === "light"
      ? `background-image: url(${overlayIllustrationLight});`
      : `background-image: url(${overlayIllustrationDark});`;
  const darkBtn = `background-color: #272c3e;
     color: #fff;
     @media (max-width: 760px) {
      background-color: #fff;
      color: #272c3e;
    }
    `;
```

I think it's a somewhat interesting solution, but I'm honestly not so sure if it's the right way forward. 

Do you have any suggestions as to how else we can change the colour while it is a background-image?

**Comment by benji011** [comment]
To be honest, I'm pretty stumped myself. But .. I like the idea of encoding it as base64 then using it as a background image vs the prop approach!
