### ISSUE TITLE
Add sticky header & change colour on scroll

### ISSUE THREAD

**Issue by benji011** [benji011/portfolio.benjaminlo.io#16]
**Is your feature request related to a problem? Please describe.**
The current header position isn't sticky so it doesn't follow the user when scrolling down.

**Describe the solution you'd like**
Ideally I want something like [this](https://benjaminlo.io/). When the web page is loaded at first the header is transparent, but after scrolling the background of the header changes colour.

### Page position at the very top
<img width="716" alt="image" src="https://user-images.githubusercontent.com/6195689/96056675-2dd04400-0ec2-11eb-86bf-a322eec0a768.png">

### After scrolling down
<img width="716" alt="image" src="https://user-images.githubusercontent.com/6195689/96056731-55bfa780-0ec2-11eb-9472-5692c0e0a3e1.png">

**Describe alternatives you've considered**
N/A

**Additional context**
It's not a highly demanded feature for me personally because I don't think a lot of my audience/users visiting will really want to click a few of the menu options just to for the site to scroll the user up & down for them. But it would be nice to have

**Comment by ankitbeniwal** [comment]
I am interested to work on this one. Assign it to me.

**Comment by benji011** [comment]
@ankitbeniwal All yours 👍 let me know if you have any questions.

**Comment by ankitbeniwal** [comment]
@benji011 sure. Might you provide me the color code for nav background?

**Comment by benji011** [comment]
@ankitbeniwal In light mode the background should be dark `#212121` and the opposite needs to be white `#ffffff`
