### ISSUE TITLE
Want to add a "GO TO TOP" button

### ISSUE THREAD

**Issue by heyankit78** [benji011/portfolio.benjaminlo.io#50]
Want to create a go-to top button for a good user experience

**Comment by benji011** [comment]
Hi @heyankit78 

Thanks for the suggestion. The site has a sticky header that pretty much does this already. Clicking any of these links jumps the user to a specific section of interest.

![image](https://user-images.githubusercontent.com/6195689/135581143-e81cd4ec-5bd0-41a2-90c6-83ddfac5fa10.png)

While I appreciate t
